// <auto-generated />
namespace SE214L22.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Initial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initial));
        
        string IMigrationMetadata.Id
        {
<<<<<<< HEAD:SE214L22.Data/Migrations/202106021716135_Initial.Designer.cs
            get { return "202106021716135_Initial"; }
=======
            get { return "202106031518538_Initial"; }
>>>>>>> TTuan-fixUI:SE214L22.Data/Migrations/202106031518538_Initial.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
